function tests = test_run_v02
tests = functiontests(localfunctions);
end


function testFlatAndStateTwoHeightContract(testCase)
testDir = string(tempname);
mkdir(testDir);
cleanup = onCleanup(@() rmdir(testDir, "s"));
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
radarCfg = fullfile(repoRoot, "Config", "profile_3d_3Azim_1ElevTx_awr2944P.cfg");
outputDir = fullfile(testDir, "output");
config = struct( ...
    "stage_id", "v02_dynamic_sea_truth", ...
    "radar", struct("model", "AWR2944PEVM", "cfg_path", radarCfg), ...
    "sea_states", [ ...
        struct("case_id", "ss0_flat", "sea_state", 0, ...
            "target_hs_m", 0, "label", "calm_glassy"), ...
        struct("case_id", "ss2_normal", "sea_state", 2, ...
            "target_hs_m", 0.30, "label", "normal_smooth_wavelets")], ...
    "installation", struct("height_m", 1, "mounting_roll_deg", 0, ...
        "mounting_pitch_deg", 5, "mounting_yaw_deg", 0), ...
    "grid", struct("x_min_m", -1, "x_max_m", 1, ...
        "y_min_m", 2, "y_max_m", 4, "spacing_m", 1), ...
    "time", struct("start_s", 0, "stop_s", 1, "step_s", 0.5), ...
    "sea_surface", struct("wind_direction_deg", 0, "fetch_m", 10000, ...
        "spectrum_resolution_m", 1, "random_seeds", 101, ...
        "amplitude_control", "scale_height_cube_to_target_hs"), ...
    "validation", struct("hs_relative_tolerance", 0.10, ...
        "flat_hs_absolute_tolerance_m", 1e-12), ...
    "output", struct("directory", outputDir));
configPath = fullfile(testDir, "test_config.json");
writeTestConfig(configPath, config);

summaries = run_v02(configPath, "test_dynamic", ...
    ["ss0_flat", "ss2_normal"], 101);
verifyEqual(testCase, numel(summaries), 2);
runDir = fullfile(outputDir, "matlab", "test_dynamic");
flatPath = fullfile(runDir, "data", "ss0_flat_seed101.h5");
normalPath = fullfile(runDir, "data", "ss2_normal_seed101.h5");
verifyTrue(testCase, isfile(flatPath));
verifyTrue(testCase, isfile(normalPath));
verifyEqual(testCase, h5readatt(normalPath, "/", "schema_version"), ...
    "awr2944p-dynamic-sea-v0.2");
verifyEqual(testCase, h5readatt(normalPath, "/", "producer"), "matlab");
verifyEqual(testCase, h5read(normalPath, "/case/sea_state"), 2);
verifyEqual(testCase, h5read(normalPath, "/case/target_hs_m"), 0.30, AbsTol=1e-12);
verifyEqual(testCase, summaries(1).achieved_hs_m, 0, AbsTol=1e-12);
verifyEqual(testCase, summaries(2).achieved_hs_m, 0.30, AbsTol=1e-10);
verifyTrue(testCase, isfile(fullfile(runDir, "run_config.json")));
verifyTrue(testCase, isfile(fullfile(runDir, "radar_profile.cfg")));
verifyTrue(testCase, isfile(fullfile(runDir, "summary.json")));

repeatSummaries = run_v02(configPath, "test_repeat", "ss2_normal", 101);
differentSummaries = run_v02(configPath, "test_different", "ss2_normal", 202);
repeatPath = fullfile(outputDir, "matlab", "test_repeat", "data", ...
    "ss2_normal_seed101.h5");
differentPath = fullfile(outputDir, "matlab", "test_different", "data", ...
    "ss2_normal_seed202.h5");
originalHeight = h5read(normalPath, "/truth/height_m");
repeatHeight = h5read(repeatPath, "/truth/height_m");
differentHeight = h5read(differentPath, "/truth/height_m");
verifyEqual(testCase, repeatHeight, originalHeight, AbsTol=0);
verifyNotEqual(testCase, differentHeight, originalHeight);
verifyEqual(testCase, repeatSummaries.achieved_hs_m, 0.30, AbsTol=1e-10);
verifyEqual(testCase, differentSummaries.achieved_hs_m, 0.30, AbsTol=1e-10);
verifyError(testCase, @() run_v02(configPath, "test_dynamic"), ...
    "run_v02:RunExists");
end


function testInvalidStateIsRejectedBeforeRunDirectoryCreation(testCase)
testDir = string(tempname);
mkdir(testDir);
cleanup = onCleanup(@() rmdir(testDir, "s"));
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
config = struct( ...
    "radar", struct("cfg_path", fullfile(repoRoot, "Config", ...
        "profile_3d_3Azim_1ElevTx_awr2944P.cfg")), ...
    "sea_states", struct("case_id", "ss4_forbidden", "sea_state", 4, ...
        "target_hs_m", 1.30, "label", "forbidden"), ...
    "sea_surface", struct("random_seeds", 101), ...
    "output", struct("directory", fullfile(testDir, "output")));
configPath = fullfile(testDir, "invalid_config.json");
writeTestConfig(configPath, config);

verifyError(testCase, @() run_v02(configPath, "must_not_exist"), ...
    "run_v02:SeaStateLimit");
verifyFalse(testCase, isfolder(fullfile(testDir, "output", "matlab", ...
    "must_not_exist")));
end


function writeTestConfig(path, config)
fileId = fopen(path, "w", "n", "UTF-8");
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", jsonencode(config, PrettyPrint=true));
end
